# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc_api import rag_pb2 as rag__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rag_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RAGServiceStub(object):
    """═══════════════════════════════════════════════════════════════
    RAG Service — основной сервис для работы с документами
    ═══════════════════════════════════════════════════════════════

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Upload = channel.unary_unary(
                '/rag.RAGService/Upload',
                request_serializer=rag__pb2.UploadRequest.SerializeToString,
                response_deserializer=rag__pb2.UploadResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/rag.RAGService/Query',
                request_serializer=rag__pb2.QueryRequest.SerializeToString,
                response_deserializer=rag__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.QueryStream = channel.unary_stream(
                '/rag.RAGService/QueryStream',
                request_serializer=rag__pb2.QueryRequest.SerializeToString,
                response_deserializer=rag__pb2.QueryChunk.FromString,
                _registered_method=True)
        self.Evaluate = channel.unary_unary(
                '/rag.RAGService/Evaluate',
                request_serializer=rag__pb2.EvalRequest.SerializeToString,
                response_deserializer=rag__pb2.EvalResponse.FromString,
                _registered_method=True)
        self.GetSummary = channel.unary_unary(
                '/rag.RAGService/GetSummary',
                request_serializer=rag__pb2.SummaryRequest.SerializeToString,
                response_deserializer=rag__pb2.SummaryResponse.FromString,
                _registered_method=True)
        self.ListCollections = channel.unary_unary(
                '/rag.RAGService/ListCollections',
                request_serializer=rag__pb2.Empty.SerializeToString,
                response_deserializer=rag__pb2.CollectionList.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/rag.RAGService/Health',
                request_serializer=rag__pb2.Empty.SerializeToString,
                response_deserializer=rag__pb2.HealthResponse.FromString,
                _registered_method=True)


class RAGServiceServicer(object):
    """═══════════════════════════════════════════════════════════════
    RAG Service — основной сервис для работы с документами
    ═══════════════════════════════════════════════════════════════

    """

    def Upload(self, request, context):
        """Загрузка документа (бинарные данные)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Задать вопрос по документам
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryStream(self, request, context):
        """Streaming: вопрос с потоковым ответом
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Evaluate(self, request, context):
        """Оценка качества RAG (RAGAS)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSummary(self, request, context):
        """Получить краткое содержание документа
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCollections(self, request, context):
        """Список коллекций
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RAGServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Upload': grpc.unary_unary_rpc_method_handler(
                    servicer.Upload,
                    request_deserializer=rag__pb2.UploadRequest.FromString,
                    response_serializer=rag__pb2.UploadResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=rag__pb2.QueryRequest.FromString,
                    response_serializer=rag__pb2.QueryResponse.SerializeToString,
            ),
            'QueryStream': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryStream,
                    request_deserializer=rag__pb2.QueryRequest.FromString,
                    response_serializer=rag__pb2.QueryChunk.SerializeToString,
            ),
            'Evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.Evaluate,
                    request_deserializer=rag__pb2.EvalRequest.FromString,
                    response_serializer=rag__pb2.EvalResponse.SerializeToString,
            ),
            'GetSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSummary,
                    request_deserializer=rag__pb2.SummaryRequest.FromString,
                    response_serializer=rag__pb2.SummaryResponse.SerializeToString,
            ),
            'ListCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCollections,
                    request_deserializer=rag__pb2.Empty.FromString,
                    response_serializer=rag__pb2.CollectionList.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=rag__pb2.Empty.FromString,
                    response_serializer=rag__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rag.RAGService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rag.RAGService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RAGService(object):
    """═══════════════════════════════════════════════════════════════
    RAG Service — основной сервис для работы с документами
    ═══════════════════════════════════════════════════════════════

    """

    @staticmethod
    def Upload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RAGService/Upload',
            rag__pb2.UploadRequest.SerializeToString,
            rag__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RAGService/Query',
            rag__pb2.QueryRequest.SerializeToString,
            rag__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rag.RAGService/QueryStream',
            rag__pb2.QueryRequest.SerializeToString,
            rag__pb2.QueryChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RAGService/Evaluate',
            rag__pb2.EvalRequest.SerializeToString,
            rag__pb2.EvalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RAGService/GetSummary',
            rag__pb2.SummaryRequest.SerializeToString,
            rag__pb2.SummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RAGService/ListCollections',
            rag__pb2.Empty.SerializeToString,
            rag__pb2.CollectionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RAGService/Health',
            rag__pb2.Empty.SerializeToString,
            rag__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
